name: Conformance K8s 1.32

on:
  workflow_run:
    workflows: ["Conformance K8s 1.33"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  conformance:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/conformance-version.yml
    with:
      k8s_version: "1.32"
      kind_version: "v0.31.0"
      kind_image: "kindest/node:v1.32.11@sha256:5fc52d52a7b9574015299724bd68f183702956aa4a2116ae75a63cb574b35af8"
