name: Conformance K8s 1.30

on:
  workflow_run:
    workflows: ["Conformance K8s 1.31"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  conformance:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/conformance-version.yml
    with:
      k8s_version: "1.30"
      kind_version: "v0.29.0"
      kind_image: "kindest/node:v1.30.13@sha256:397209b3d947d154f6641f2d0ce8d473732bd91c87d9575ade99049aa33cd648"
