name: Conformance K8s 1.29

on:
  workflow_dispatch:

jobs:
  conformance:
    uses: ./.github/workflows/conformance-version.yml
    with:
      k8s_version: "1.29"
      kind_version: "v0.27.0"
      kind_image: "kindest/node:v1.29.14@sha256:8703bd94ee24e51b778d5556ae310c6c0fa67d761fae6379c8e0bb480e6fea29"
