name: Conformance K8s 1.23

on:
  workflow_dispatch:

jobs:
  conformance:
    uses: ./.github/workflows/conformance-version.yml
    with:
      k8s_version: "1.23"
      kind_version: "v0.22.0"
      kind_image: "kindest/node:v1.23.17@sha256:14d0a9a892b943866d7e6be119a06871291c517d279aedb816a4b4bc0ec0a5b3"
