name: Conformance K8s 1.31

on:
  workflow_dispatch:

jobs:
  conformance:
    uses: ./.github/workflows/conformance-version.yml
    with:
      k8s_version: "1.31"
      kind_version: "v0.31.0"
      kind_image: "kindest/node:v1.31.14@sha256:6f86cf509dbb42767b6e79debc3f2c32e4ee01386f0489b3b2be24b0a55aac2b"
